#include "export/mesh_exporter.h"

#include <fstream>
#include <iomanip>
#include <cstdio>
#include <filesystem>

bool exportOBJ(const Mesh& mesh, const std::string& path) {
    char buf[1 << 20];
    std::ofstream out(path, std::ios::out);
    if (!out) {
        fprintf(stderr, "[OBJ] Cannot open %s for writing\n", path.c_str());
        return false;
    }
    out.rdbuf()->pubsetbuf(buf, sizeof(buf));
    out << std::fixed << std::setprecision(6);

    int nv = mesh.num_vertices();
    int nf = mesh.num_faces();
    bool has_colors = (int)mesh.colors.size() == nv;
    bool has_normals = (int)mesh.normals.size() == nv;
    bool has_texcoords = (int)mesh.texcoords.size() == nv;

    // Header
    out << "# Generated by cuda_3d_recon\n";
    out << "# Vertices: " << nv << ", Faces: " << nf << "\n";

    // MTL file if texcoords present
    if (has_texcoords) {
        namespace fs = std::filesystem;
        std::string mtl_name = fs::path(path).stem().string() + ".mtl";
        out << "mtllib " << mtl_name << "\n";

        // Write companion .mtl
        std::string mtl_path = (fs::path(path).parent_path() / mtl_name).string();
        std::ofstream mtl(mtl_path);
        if (mtl) {
            mtl << "newmtl default\n";
            mtl << "Ka 0.2 0.2 0.2\n";
            mtl << "Kd 0.8 0.8 0.8\n";
            mtl << "Ks 0.0 0.0 0.0\n";
            mtl << "d 1.0\n";
        }
    }

    // Vertices (with optional colors as extension)
    for (int i = 0; i < nv; i++) {
        out << "v " << mesh.vertices[i].x() << " "
                    << mesh.vertices[i].y() << " "
                    << mesh.vertices[i].z();
        if (has_colors) {
            out << " " << mesh.colors[i].x() << " "
                       << mesh.colors[i].y() << " "
                       << mesh.colors[i].z();
        }
        out << "\n";
    }

    // Texture coordinates
    if (has_texcoords) {
        for (int i = 0; i < nv; i++) {
            out << "vt " << mesh.texcoords[i].x() << " "
                         << mesh.texcoords[i].y() << "\n";
        }
    }

    // Normals
    if (has_normals) {
        for (int i = 0; i < nv; i++) {
            out << "vn " << mesh.normals[i].x() << " "
                         << mesh.normals[i].y() << " "
                         << mesh.normals[i].z() << "\n";
        }
    }

    // Faces (1-indexed!)
    for (int i = 0; i < nf; i++) {
        int v0 = mesh.faces[i].x() + 1;
        int v1 = mesh.faces[i].y() + 1;
        int v2 = mesh.faces[i].z() + 1;

        if (has_texcoords && has_normals) {
            out << "f " << v0 << "/" << v0 << "/" << v0 << " "
                        << v1 << "/" << v1 << "/" << v1 << " "
                        << v2 << "/" << v2 << "/" << v2 << "\n";
        } else if (has_normals) {
            out << "f " << v0 << "//" << v0 << " "
                        << v1 << "//" << v1 << " "
                        << v2 << "//" << v2 << "\n";
        } else if (has_texcoords) {
            out << "f " << v0 << "/" << v0 << " "
                        << v1 << "/" << v1 << " "
                        << v2 << "/" << v2 << "\n";
        } else {
            out << "f " << v0 << " " << v1 << " " << v2 << "\n";
        }
    }

    printf("[OBJ] Exported mesh: %d vertices, %d faces → %s\n", nv, nf, path.c_str());
    return true;
}
